# Generated by Django 5.1.5 on 2025-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('createdIn', models.DateTimeField(auto_now_add=True)),
                ('updatedIn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
